// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSdjCOnUZCDk25eiavd9Q37ThQzmc8nw8',
    appId: '1:736475837178:web:b2508e735ca4a896c38f43',
    messagingSenderId: '736475837178',
    projectId: 'paperlesspocket-5418',
    authDomain: 'paperlesspocket-5418.firebaseapp.com',
    storageBucket: 'paperlesspocket-5418.appspot.com',
    measurementId: 'G-N6H3BL6M38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAOYfgKpAlVWywdLVefNwS4KmcGzlUKs',
    appId: '1:736475837178:android:357dfe0424df94b2c38f43',
    messagingSenderId: '736475837178',
    projectId: 'paperlesspocket-5418',
    storageBucket: 'paperlesspocket-5418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLutB2csXgzyFus7bugp_x-yi_X-N9k_A',
    appId: '1:736475837178:ios:6e0f50ec5379613fc38f43',
    messagingSenderId: '736475837178',
    projectId: 'paperlesspocket-5418',
    storageBucket: 'paperlesspocket-5418.appspot.com',
    iosClientId: '736475837178-iqirkar43cac6go47kk9c5k2sh0papsp.apps.googleusercontent.com',
    iosBundleId: 'com.atinity.ppocket',
  );
}
